name: Flatpak

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: acroread.flatpak
        manifest-path: com.adobe.Reader.yaml
        cache-key: flatpak-builder-${{ github.sha }}
